name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.5" # Stable Flutter version
          clean: true

      - name: Install dependencies
        run: flutter pub get

      - name: Clean Flutter cache
        run: flutter clean

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Upload Web Build
        uses: actions/upload-artifact@v3
        with:
          name: flutter-web-build
          path: build/web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
